name = "GEO.visibility"
client_id = "058ce5728ebfc9f888708fe67411eb60"
application_url = "https://geo-v-backend.onrender.com"
embedded = false

[access_scopes]
  scopes = "read_products,write_products,read_themes,write_themes"

[auth]
  redirect_urls = [
    "https://geo-v-backend.onrender.com/oauth/callback"
  ]

[webhooks]
  api_version = "2025-01"

[pos]
  embedded = false

[[extensions]]
  path = "extensions/geo-schema"
